SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Player
PLAYER_RADIUS = 20
LINE_WIDTH =2

# Turn speed
PLAYER_TURN_SPEED = 300

# player speed
PLAYER_SPEED = 200

# player acceleration (thrust rate; PLAYER_SPEED acts as the resulting speed cap)
PLAYER_ACCELERATION = 300

# Asteroid
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Shot
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

# Scoring - smaller asteroids are worth more points
SCORE_ASTEROID_SMALL = 100
SCORE_ASTEROID_MEDIUM = 50
SCORE_ASTEROID_LARGE = 20